name = "arachnid-feedback"
main = "src/index.ts"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "arachnidagent.com/api/*", zone_name = "arachnidagent.com" }
]

kv_namespaces = [
  { binding = "ARACHNID_KV", id = "f78521e41f184d16969bb4b0a70fa859" }
]

[vars]
ADMIN_TOKEN = "milehighwombat"
